# To get started with Dependabot version updates, you'll need to specify which
# package ecosystems to update and where the package manifests are located.
# Please see the documentation for all configuration options:
# https://docs.github.com/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file

version: 2
updates:
  - package-ecosystem: "npm" # See documentation for possible values
    directories:
      - "/"
      - "/demo"
    schedule:
      interval: "daily"
      time: "03:19" # UTC
      timezone: "Europe/Berlin"
    ignore:
      - dependency-name: "npm"
        versions: ["<10.0.0", ">=11.0.0"]
    groups:
      all:
        patterns:
          - "*"
    commit-message:
      prefix: "dependabot"
      prefix-development: "dependabot"
