name: Changeset auto-release

on:
  schedule:
    # - cron: "14 4 1 * *" # At 04:28 on day-of-month 1 (UTC)
    # Just for testing purposes - run every 5 minutes
    - cron: "*/5 * * * *" # Every 5 minutes

permissions:
  contents: read
  pull-requests: write

jobs:
  # echo:
  #   runs-on: ubuntu-latest
  #   steps:
  #     - run: ${{ tojson(github) }}
  #       shell: cat {0}
  merge-release-pr:
    uses: kt-public/github-actions/.github/workflows/wc-changeset-auto-release.yml@v1
    secrets:
      WORKFLOW_APP_ID: ${{ secrets.WORKFLOW_APP_ID }}
      WORKFLOW_APP_PRIVATE_KEY: ${{ secrets.WORKFLOW_APP_PRIVATE_KEY }}
