name: Release

on:
  workflow_run:
    workflows: ['CI']
    types:
      - completed
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: write # to create release (changesets/action)
  id-token: write # OpenID Connect token needed for provenance
  pull-requests: write # to create pull request (changesets/action)

jobs:
  # echo:
  #   runs-on: ubuntu-latest
  #   steps:
  #     - run: ${{ tojson(github) }}
  #       shell: cat {0}
  release:
    # prevents this action from running on forks
    if: >-
      github.repository == 'kt-npm-modules/npm-typescript-template' && 
      github.ref == 'refs/heads/main' && 
      github.event.workflow_run.event == 'push' && 
      github.event.workflow_run.conclusion == 'success'
    uses: kt-workflows/npm-release/.github/workflows/main.yml@v1
    with:
      matrix-node-version: ${{ vars.MATRIX_NODE_VERSION }}
    secrets:
      WORKFLOW_APP_ID: ${{ secrets.WORKFLOW_APP_ID }}
      WORKFLOW_APP_PRIVATE_KEY: ${{ secrets.WORKFLOW_APP_PRIVATE_KEY }}
      NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
